name: Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    uses: esphome/workflows/.github/workflows/build.yml@main
    with:
      files: |
        samples/basic-beep-detector/basic-beep-detector.yaml
        samples/gree-ac-remote/ac-remote.yaml
      esphome-version: latest
